obj-$(CONFIG_ARM64)	+=	cpu_ops.o
obj-$(CONFIG_QCOM_GSBI)	+=	qcom_gsbi.o
obj-$(CONFIG_QCOM_PM)	+=	spm.o
obj-$(CONFIG_QCOM_SMD) +=	smd.o
obj-$(CONFIG_QCOM_SMEM) +=	smem.o
obj-$(CONFIG_QCOM_IPCRTR_STUB)	+= ipcrtr_stub.o
obj-$(CONFIG_QCOM_WCNSS_CTRL) += wcnss_ctrl.o
